name: opi-lab-regression
on: workflow_dispatch
jobs:
  opi-lab-job:
    runs-on: self-hosted
    steps:
        - uses: actions/checkout@v1
        - name: pytest-run1
          run: ls
        - name: pytest-run2
          run: pwd
        - name: pytest-run3
          run: pip install -r ./demos/tgen/requirements.txt
        - name: pytest-run4
          run: pytest -s ./demos/tgen/test_tgen_demo.py
  
  opi-ansible:
    runs-on: self-hosted
    steps:
        - name: nvidia bf-2 fw update using ansible
          run: docker run --rm -it ghcr.io/opiproject/ansible-opi-dpu:main 172.22.4.2 --module-name include_role --args name=bmc_fw_update -vvv -i "172.22.4.2," -e dpu_bmc_username='root' -e dpu_bmc_password='123456'
